# Increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Mod Properties
mod_id=carpetskyadditions
mod_name=Carpet Sky Additions Revised
repository=https://github.com/TreeOfSelf/CarpetSkyAdditions
mod_version=6.7.0
java_version=25
# Fabric Properties
# see https://fabricmc.net/develop/
minecraft_version=26.3
compatible_minecraft_versions=>=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
# Fabric Api
fabric_version=0.161.0+26.3
# see https://masa.dy.fi/maven/carpet/fabric-carpet/
carpet_core_version=26.3
# see https://linkie.shedaniel.me/dependencies
cloth_config_version=26.3.159
modmenu_version=21.0.0
